language: node_js

node_js:
  - 4
  - 6

env:
  - ARANGODB_VERSION=2.8.11
  - ARANGODB_VERSION=3.1.18

before_install:
  - chmod +x ./test/travis/setup_arangodb.sh
  - ./test/travis/setup_arangodb.sh

after_success:
  - grunt coveralls

after_script:
  - ./test/travis/teardown_arangodb.sh